- name: Run cowsay before main tasks
  ansible.builtin.command: /usr/games/cowsay "This is server {{ server_name }}!"
  register: cowsay_result

- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  tags: [install, install_nginx]

- name: creat app directory
  file:
    path: "{{root_dir}}"
    state: directory
  tags: [copy]

- name: copy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{root_dir}}/index.html"
  tags: [copy, copy_index]

- name: update nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/app
  notify:
        - restart nginx
  tags: [update, update_nginx_conf, nginx]

- name: enable nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/app
    dest: /etc/nginx/sites-enabled/app
    state: link
  tags: [update, update_nginx_conf, nginx]    
