[servers:children]
docker
cloud-computing

[docker]
yc-toolbox

[cloud-computing]
my-vm server_name=my-vm

[local]
localhost ansible_connection=local

[nginx]
89.169.137.249 ansible_user=yamusicplus server_name=nginx
