- hosts: cloud-computing
  become: yes
  #gather_facts: no
  vars:
    user_name:
      - jaime
      - sansa
      - robert
    
  tasks:
  #- block:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      tags: [install, install_git, update_cache]
      

    - name: install Git    
      ansible.builtin.apt:
        name: git
        state: present
      tags: [install, install_git]

    - name: add users
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
        state: present
      loop: '{{ user_name }}'
      tags: add_users

    - name: update git config
      ansible.builtin.template:
        src: files/.gitconfig.j2
        dest: '/home/{{ item }}/.gitconfig'
      loop: '{{ user_name }}'
      tags: [update, update_git_conf]

    - name: creat .ssh directory
      file:
        path: '/home/{{ item }}/.ssh/'
        state: directory
      loop: '{{ user_name }}'
      tags: [update, update_git_ssh, ssh]

    - name: update ssh key
      ansible.builtin.copy:
        src: files/id_ed25519.pub
        dest: '/home/{{ item }}/.ssh/authorized_keys'
      loop: '{{ user_name }}'
      tags: [update, update_git_ssh, ssh]
    #when: ansible_facts["distribution"] == "Debian"    