- hosts: cloud-computing
  become: yes
  vars:
    nginx_port: 8080
    root_dir: /etc/nginx/sites-available 

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      tags: [install, install_nginx]

    - name: copy index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
      tags: [copy, copy_index]

    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: "{{root_dir}}/app"
      notify:
        - restart nginx
      tags: [update, update_nginx_conf, nginx]  

  handlers:
        - name: restart nginx
          ansible.builtin.service:
            name: nginx
            state: restarted    