- hosts: cloud-computing
  become: yes

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      tags: [install, install_nginx]

    - name: copy index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
      tags: [copy, copy_index]

    - name: update nginx config
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      tags: [update, update_nginx_conf, nginx]  

  handlers:
        - name: restart nginx
          ansible.builtin.service:
            name: nginx
            state: restarted    