- hosts: cloud-computing
  become: yes

  tasks:
    - name: remove Git
      ansible.builtin.apt:
        name: git
        state: absent
      tags: [remove, remove_git]

    - name: remove Make
      ansible.builtin.apt:
        name: make
        state: absent
      tags: [remove, remove_make]

    - name: remove Nodejs
      ansible.builtin.apt:
        name: nodejs
        state: absent
      tags: [remove, remove_nodejs]       
    
    - name: remove users
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - aria
        - sansa
        - tirion 
      tags: [remove, remove_users]