- hosts: my-vm
  become: yes
  gather_facts: no
  vars:
    users:
      - sansa

  tasks:
    - name: add ssh key
      ansible.posix.authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'id_ed25519.pub') }}"
      loop: "{{ users }}"
      tags: [add_ssh]

    - name: remove ssh key
      ansible.posix.authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'id_ed25519.pub') }}"
        state: absent
      loop: "{{ users }}"
      tags: [remove_ssh]