- name: add users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    state: present
  loop: '{{ users }}'
  tags: [add_users]

- name: update git config
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: '/home/{{ item.name }}/.gitconfig'
  loop: '{{ users }}'
  tags: [update, update_git_conf]

- name: creat .ssh directory
  file:
    path: '/home/{{ item.name }}/.ssh/'
    state: directory
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
    mode: '0700'
  loop: '{{ users }}'
  tags: [update, update_git_ssh, ssh]

- name: update ssh key
  ansible.builtin.copy:
    src: id_ed25519.pub
    dest: '/home/{{ item.name }}/.ssh/authorized_keys'
    owner: '{{ item.name }}'
    mode: '0600'
  loop: '{{ users }}'
  tags: [update, update_git_ssh, ssh] 